oVirt/go-ovirt-client

client.go, client_testconnection.go
This change adds a function to perform a connection test.
Based on #5
=> Connection test

errors.go, new.go, new_test.go
This PR incorporates a number of really minor code fixes that don't fit anywhere else.
=> Minor fixes

client_disk.go
This change adds the Remove function directly on the Disk object for easier access.
=> Added disk remove proxy function

client_disk.go
This change adds the Download and StartDownload functions directly on the Disk object for easier access.
=> Added disk download proxy function

client_disk.go
This change adds the `Sparse()` function to the Disk object.
=> Added Sparse to Disk objects

CONTRIBUTING.md, README.md, scripts/rest.go, test_helper.go
Added CONTRIBUTING.md and some related quality-of-life improvements for testers.
=> Added CONTRIBUTING.md

client_disk_attachment_test.go, client_nic_test.go, client_vm.go, client_vm_test.go, client_vm_update.go, mock_vm_update.go
This change adds the ability to update the VM name and comment.
=> Added VM update

errors.go
Added the HasErrorCode convenience function to make it easier to identify errors.
=> Added HasErrorCode

client_disk.go, client_disk_attachment.go, client_host.go, client_storagedomain.go, client_vm.go
This change adds a `*Values()` function to each enum-style const to allow fetching all possible values.
=> Added enum const values functions

client_disk_attachment_test.go, client_nic.go, client_nic_create.go, client_nic_test.go, client_vm.go, client_vm_test.go, mock_nic_create.go
=> Added optional NIC parameters

client_nic.go, client_nic_create.go, client_vm.go, mock_nic_create.go
Changing CreateNIC parameter order to make them more logical.
=> Reordered CreateNIC parameters

client_vnicprofile.go, client_vnicprofile_create.go, client_vnicprofile_remove.go, client_vnicprofile_test.go, mock_vnicprofile_create.go, mock_vnicprofile_remove.go
This PR adds creation and removal for VNIC profiles.
=> Create VNIC profile

tls.go
Add a new "TLSWithCertPool" function to allow creation of a TLS provider with an existing x509.CertPool. The use case is CDI, where the HTTP importer already has a bunch of code that correctly sets up a CertPool for system certificates, user-supplied certificates, and proxy certificates. I would like to avoid duplicating that code in the ImageIO importer, as I am trying to help convert it to use go-ovirt-client one piece at a time.
The only other way I could think to do this was to iterate over the HTTP client's CertPool and add them one at a time with CACertsFromMemory, after converting each one back to PEM format. But it seemed simpler just to be able to import the whole pool, if that's an okay thing to do.
Yes
Yes
=> Allow TLS certificates from existing pool.

newmock.go, test_helper.go
This change refactors the test helper to make calling it more flexible. It also adds a second storage domain for testing.
yes
yes
=> Refactoring the test helper

client_template.go, client_template_get_blank.go, const.go, mock_template_get_blank.go, newmock.go, test_helper.go
This change adds the necessary scaffolding for later blank template detection.
Yes
Yes
=> Added scaffolding for blank template detection

client_vm.go, client_vm_create.go, client_vm_test.go, mock_vm_create.go
This change lets you set the CPU topology when creating a VM.
Yes
Yes
=> VM CPU topology

client_disk_attachment_test.go, client_disk_uploadimage_test.go, client_vm.go, client_vm_shutdown.go, client_vm_start.go, client_vm_stop.go, client_vm_test.go, client_vm_wait_for_status.go, mock_vm_shutdown.go, mock_vm_start.go, mock_vm_stop.go, mock_vm_wait_for_status.go
This PR fixes #74 and adds VM start, stop, shutdown, and waiting for status.
Yes
Yes
=> VM start, stop, shutdown, and wait

client_disk_uploadimage_test.go, client_vm_shutdown.go, client_vm_start.go, client_vm_stop.go, client_vm_test.go
This PR adds minor improvements to #74 and #75.
Yes
Yes
=> Fixes #74: Minor patches for VM start/stop

client_helpers.go, client_vm.go, client_vm_search.go, client_vm_search_test.go, mock_vm_search.go
This PR adds the first search function.
Yes
Yes
=> Added VM search capability

client_disk_attachment_test.go, client_storagedomain.go, client_storagedomain_get_disk.go, client_storagedomain_remove_disk.go, mock_storagedomain_get_disk.go, mock_storagedomain_remove_disk.go
Introducing Storage domain methods for querying and removal disks.
=> introduce storage domain disks methods

client_template.go, client_template_create.go, client_template_get.go, client_template_remove.go, client_template_test.go, client_template_wait_for_status.go, client_vm.go, client_vm_create.go, codetemplates/client_ITEM_get.go.tpl, codetemplates/mock_ITEM_get.go.tpl, const.go, mock.go, mock_template_create.go, mock_template_get.go, mock_template_remove.go, mock_template_wait_for_status.go, mock_vm_create.go, newmock.go, scripts/rest.go, test_helper.go
This PR adds basic template creation. The full implementation will follow in a later PR.
Yes
Yes
=> Template creation

client_nic_create_test.go, client_nic_update_test.go, client_template.go, client_template_get_blank.go, client_template_get_blank_test.go, client_template_test.go, client_vm.go, client_vm_test.go, const.go, mock_template_create.go, mock_template_get_blank.go, mock_template_remove.go, mock_vm_create.go, mock_vm_update.go, newmock.go
This PR adds CPU handling to templates in live and mock. It also adds correct handling for VMs when a template is used.
Yes
Yes
=> Template create CPU

client_disk.go, client_disk_attachment_test.go, client_disk_create.go, client_disk_downloadimage_test.go, client_disk_helper_imagetransfer.go, client_disk_list_by_alias_test.go, client_disk_test.go, client_disk_uploadimage_test.go, client_nic_create_test.go, client_nic_remove.go, client_nic_update_test.go, client_template_get_blank_test.go, client_template_remove.go, client_template_test.go, client_vm_remove.go, client_vm_search_test.go, client_vm_test.go, client_vnicprofile_test.go, credential_shift_test.go, new_test.go, retry.go
This PR fixes timeouts and switches tests to run in parallel.
Yes
Yes
=> Timeout fix

client_testconnection.go, credential_shift_test.go, errors.go, new.go
This PR adds a function to test if the oVirt connection is alive.
Yes
Yes
=> Added function to test oVirt connect

client_vm_test.go
This PR adds a random VM name to the creation test to avoid collisions.
Yes
Yes
=> Random ID for VM used for testing

client_disk.go, client_disk_helper_imagetransfer.go, client_disk_util.go, client_storagedomain.go, client_template.go, client_template_copy_disk.go, client_template_test.go, mock_disk_util.go, mock_template_copy_disk.go
this method will allow copying disks between different storage domains.
=> introduce CopyDiskToStorageDomain method to ovirt-client

.github/workflows/build.yml
This change updates to [gotestfmt v2](https://github.com/haveyoudebuggedit/gotestfmt) for better test attribution.
Yes
Yes
=> Update to gotestfmt v2

client_vm_remove_test.go, client_vm_test.go, mock_disk_remove.go, mock_vm_create.go, mock_vm_remove.go
This PR fixes #81 where the VM deletion behavior was incorrectly simulated.
Yes
Yes
=> Fixes #81: Simulate VM deletion behavior

client_vm.go, client_vm_optimize_pinning.go, mock_vm_optimize_pinning.go
This PR adds an API call to automatically optimize CPU and NUMA pinning.
Note: this PR has no tests because it has no observable effect.
Yes
Yes
=> Fixes #94: CPU and NUMA pinning

client.go, client_tag.go, client_tag_create.go, client_tag_get.go, client_tag_list.go, client_tag_remove.go, client_tag_test.go, client_vm.go, client_vm_add_tag.go, client_vm_search.go, mock.go, mock_tag_create.go, mock_tag_get.go, mock_tag_list.go, mock_tag_remove.go, mock_vm_add_tag.go, newmock.go
introduce tags support for vms
=> introduce tags support to VMs

client_template_copy_disk.go, client_template_test.go
This PR fixes the incorrect error handling with template copies.
Yes
Yes
=> Fixed template copy error handling and test messages.

client_vm.go, client_vm_create.go, client_vm_test.go, mock_vm_create.go
This PR partially fixes #62 and adds hugepages options to VM creation.
Yes
Yes
=> Partially fixes #62: Add huge pages support for VM creation

client_nic_create.go, client_nic_create_test.go, client_nic_test.go, mock_nic_create.go
This PR fixes #84 and add function that check NIC unique names.
add also a test that check user can't create duplicate nic with same name.
yes
=> Add function that check NIC unique names.

CONTRIBUTING.md, doc.go
Adding some refinement of how to configure the environment for the first time.
yes
yes
=> Adding some refinement of how to configure the environment

affinitygroup.go, affinitygroup_create.go, affinitygroup_get.go, affinitygroup_list.go, affinitygroup_remove.go, affinitygroup_test.go, affinitygroup_vm_add.go, affinitygroup_vm_remove.go, client.go, client_cluster.go, client_cluster_get.go, client_datacenter.go, client_host.go, client_vm.go, client_vm_create.go, client_vm_test.go, codetemplates/v2/ITEM_get.go.tpl, codetemplates/v2/ITEM_list.go.tpl, mock.go, mock_cluster_get.go, mock_datacenter.go, mock_vm_create.go, mock_vm_start.go, mock_vm_stop.go, newmock.go, test_helper.go
This PR fixes #93 and adds support for affinity groups.
Yes
Yes
=> Fixes #93: Affinity group support

client.go, feature.go, feature_test.go
This PR adds feature flags that can be queried to determine the capabilities of the oVirt engine.
Yes
Yes
=> Fixes #116: feature flags

client_vm.go, client_vm_test.go, vm_get_by_name.go
This PR adds GetVMByName Method to the VM Client.
Yes
Yes
=> adding GetVMByName method to the VMClient

client_template.go, client_template_test.go, template_get_by_name.go
This PR adds GetTemplateByName Method to the Template Client.
Yes
Yes
=> adding GetTemplateByName method to the Client (#115)

.github/workflows/build.yml, .github/workflows/tr-master-suite-trigger.yaml
Nicer GitHub Actions messaging.
Yes
Yes
=> Nicer GitHub Actions communication

client_disk_downloadimage_test.go
Fixing a missing embedding of the test image.
Yes
Yes
=> Fix testimage

client_template_test.go, client_vm.go, client_vm_create.go, client_vm_test.go, mock_vm_create.go
Adding support for cloning a VM from the template instead of linking to it.
Yes
Yes
=> Implemented VM cloning from template

client_nic.go, client_storagedomain.go, client_vm.go
This PR fixes several incorrect comments.
Yes
Yes
=> Comment fixes

client_vm.go, client_vm_create.go, client_vm_test.go, mock_vm_create.go
This PR fixes #138 and adds the memory field to the VM object.
Yes
Yes
=> adding Memory methods (#138)

client_tag_test.go, client_vm.go, client_vm_add_tag.go, mock_vm_add_tag.go
Add method to attach VM to a tag using its tagName
Yes
Yes
=> Fixes #135 - Attach VM to a tag by name

errors.go
This PR fixes #56 and identifies hot-plug issues correctly.
Yes
Yes
=> Fixes #56: Identify hot-plug errors

new.go
This change updates the username validation to match the 4.5 schema.
Yes
Yes
=> Updated username validation to match oVirt 4.5

affinitygroup.go, affinitygroup_create.go, affinitygroup_get.go, affinitygroup_get_by_name.go, affinitygroup_get_by_name_test.go, errors.go
This PR lets you get affinity groups by name and fixes #149.
Yes
Yes
=> Fixes #149: Get affinity groups by name

affinitygroup_vm_add.go
This PR fixes #153 and adds handling for false negatives on older oVirt versions.
Yes
Yes
=> Fixes #153: handle false negatives when adding a VM to AG

client_vm.go, client_vm_create.go, client_vm_test.go, mock_vm_create.go
This change fixes #137 and adds support for defining a placement policy on VM creation.
Yes
Yes
=> Fixes #137: Placement policy support for VM creation

client_vm.go, client_vm_create.go, client_vm_test.go, errors.go, mock_vm_create.go
This PR fixes #91 and adds guaranteed memory support.
Yes
Yes
=> Fixes #91: Adding guaranteed memory support

client_tag.go, client_tag_create.go, client_tag_test.go, mock_tag_create.go
This PR makes the description field of the tag optional.
Yes
Yes
=> Fixes #158: Optional tag description

client.go, client_vm.go, client_vm_create.go, client_vm_test.go, instancetype.go, instancetype_get.go, instancetype_list.go, instancetype_test.go, mock.go, mock_vm_create.go, newmock.go
This PR fixes #163 and adds instance type handling.
Yes
Yes
=> Fixes #163: Add instance type ID to VM

client_template_copy_disk.go, client_vm.go, client_vm_create.go, client_vm_test.go, mock_vm_create.go
This PR fixes #178 and adds the storage domain to the VM disk parameters.
Yes
Yes
=> Fixes #178: VM creation disk parameters

client_vm_stop_test.go
Added test for stopping already stopped VM
Yes
Yes
=> Added test for stopping already stopped VM

README.md
Updated README example for creating a test helper manually. 
Yes
Yes
=> updated test helper example

client.go, mock.go, newmock.go, vm.go, vm_create.go, vm_graphics_console.go, vm_graphics_console_list.go, vm_graphics_console_remove.go, vm_graphics_console_test.go, vm_remove.go
This PR implements graphics console handling (listing and removing only). See oVirt/terraform-provider-ovirt#347
**Note:** The live tests are currently not passing. @eslutsky do you know how to make the oVirt engine attach a graphics console apart from adding it explicitly?
Yes
Yes
=> Implement graphics console handling

errors.go
This PR adds identification for the "Cannot run VM without at least one bootable disk." error message as a permanent error.
Yes
Yes
=> Identify 'cannot run VM' errors

disk_create.go
This PR fixes the predictable correlation ID when creating disks.
Yes
Yes
=> Fixed disk creation correlation ID

.github/workflows/go-suite-trigger.yaml
suite is renamed in https://github.com/oVirt/ovirt-system-tests/pull/79
=> Use go-suite-master for OST testing

disk_downloadimage.go, disk_uploadimage.go, doc.go, retry.go
This PR changes the retry log level to info.
Yes
Yes
=> Changing log levels to info

vm_create.go
Minor fix for error message.
Yes
Yes
=> Minor fix for error message

feature.go, feature_test.go
Ths PR adds a feature constant for `Placement Policy`, which is required to check in [terraform-provider-ovirt issue 391](https://github.com/oVirt/terraform-provider-ovirt/issues/391). 
yes
yes
=> added feature flag for placement policy

vm.go, vm_create.go, vm_test.go
This PR adds serial console support.
yes
yes
=> Added serial console support

template_get_blank.go
This PR adds a more descriptive error message as requested by @mburman5 
Yes
Yes
=> More descriptive blank template error message

affinitygroup.go, affinitygroup_create.go, affinitygroup_test.go, vm.go, vm_create.go, vm_get.go, vm_get_by_name.go, vm_list.go, vm_search.go, vm_update.go
This PR adds the ability to set descriptions on affinity groups.
Yes
Yes
=> Affinity group description

vm_ip_wait.go
This change adds an explicit error message when a required IP address is not found that checks if the VM has a NIC attached and warns the user if that is not the case.
Yes
Yes
=> Fixes #215: Better error message on missing IP address

vm.go, vm_ip_get_nonlocal.go
This PR adds the ability to get all non-local IPs instead of waiting for them.
Yes
Yes
=> Added the ability to get (not just wait for) non-local IP addresses

disk_attachment_create.go, disk_attachment_test.go, template_test.go
This PR fixes the incorrect behavior of active and bootable on disk attachments.
Yes
Yes
=> Fixing active and bootable behavior on disk attachments

README.md
Preparing for v1.0.0 release
Yes
Yes
=> Removed notice about early development

README.md
Update go-ovirt-client to go-ovirt-client-log/v3
=> Readme: update go-ovirt-client to go-ovirt-client-log/v3

newmock.go, storagedomain.go, storagedomain_list.go, util_test_helper.go
This PR attempts to fix https://github.com/oVirt/go-ovirt-client/issues/228
yes
yes
=> filter for storage domain nfs in testhelper setup

.github/workflows/build.yml
This PR disables the CI step to build the RPM for testing with the oVirt System test. 
yes
yes
=> fix ci rpm build
