client_disk.go, client_storagedomain.go, mock_disk_uploadimage.go
This change fixes #2 where an uint overflows on 32 bit platforms.
Yes
Yes
=> Fixes #2: constant overflows uint on 32 bit platforms

README.md, client_test.go, go.mod
This change moves the Go package name to lower case `ovirt` to avoid problems with vendoring.
=> Changes to lower case package name to avoid problems with vendoring

client_disk_helper_imagetransfer.go, errors.go
This changes the image transfer to abort if the disk status is "illegal", which is a non-recoverable state.
=> No retry on disk status "illegal"

client_disk_attachment_test.go
This change fixes a broken test that wasn't caught due to a misconfiguration.
=> Fixed broken tests

client_datacenter.go, client_disk.go, client_host.go, client_network.go, client_nic.go, client_storagedomain.go, client_vm.go, client_vnicprofile.go
This change splits the data objects (e.g. VM) into two parts to satisfy the Interface Segregation Principle (e.g. VM and VMData). This will allow implementers (e.g. the Terraform provider) to only use the smaller interface for tests and other use cases.
=> Split data objects

client_disk.go, client_disk_create.go, client_disk_downloadimage_test.go, client_disk_test.go, client_disk_update.go, client_disk_uploadimage.go, client_disk_uploadimage_test.go, example_vm_uploadimage_test.go, mock_disk.go, mock_disk_update.go, mock_disk_uploadimage.go
This change allows updating disk aliases and serves as a baseline for future update operations. Based on #38
=> Disk update

tls.go
When addCertsFromDir encounters a sub-directory, ignore it instead of immediately returning. I tried using CACertsFromDir in CDI, and it was failing because there were some irrelevant directories listed before ca.pem. This seems like the simplest way to fix it, unless there is a particular reason for the current behavior?
Yes.
Yes.
=> Ignore sub-directories in addCertsFromDir.

client_disk_downloadimage_test.go, client_disk_uploadimage_test.go, example_vm_uploadimage_test.go, scripts/rest.go
This change fixes linting errors in #64 by properly annotating gosec failures.
yes
yes
=> Fixing gosec linting errors

README.md, doc.go, tls.go, tls_test.go
This change adds functionality to #60 to allow the certificate pool to be actually used. It also moves the TLS initialization to a builder function to make it more flexible.
yes
yes
=> Tests and docs for loading TLS from a cert pool

.golangci.yml
I propose removing the requirement to run `gofumpt` on the code. Instead, just simply `gofmt` will do to make it more contribution-friendly.
yes
yes
=> Removed annoying gofumpt requirement

client_disk.go, mock_disk.go, mock_disk_create.go
This change removes the `StorageDomain()` function and adds the `StorageDomains()` function to more accurately reflect how oVirt handles disk and storage domain relations. The actual testing of multiple storage domain behavior should be handled in #51.
Yes
Yes
=> Removing StorageDomain() and adding StorageDomains() on Disk objects

client_disk_attachment_test.go, client_nic_create_test.go, client_nic_update_test.go, client_vm.go, client_vm_create.go, client_vm_test.go, client_vm_update.go, example_vm_create_test.go, mock_vm_create.go
The name parameter was erroneously removed as a required parameter in the past. This change re-adds the name parameter.
Yes
Yes
=> Re-adding name as a required VM creation parameter

mock_disk_remove.go
This change adds a check to disallow removing disks that are currently attached to a running VM.
Yes
Yes
=> Added check to disallow removing disks from running VMs

.github/workflows/build.yml
This PR removes builds on pushes to non-main branches to avoid CodeQL complains and conserve resources.
Yes
Yes
=> Removing builds on push on non-main branch

.github/workflows/build.yml, .github/workflows/codeql.yml
This PR moves the CodeQL runs to a different workflow because it was causing problems in runs.
Yes
Yes
=> Running CodeQL on a separate workflow

client_vm.go, client_vm_create.go, client_vm_test.go, mock_vm_create.go
this change is required for launching VMs with a custom_script  (cloud_init and ignition)
=> introduce VM Initialization Support

client_disk_downloadimage_test.go, client_disk_uploadimage_test.go, example_vm_uploadimage_test.go, scripts/rest.go
This change fixes the linting errors introduced in golangci-lint 1.44.0.
Yes
Yes
=> Fixing golangci-lint errors since 1.44.0 upgrade

client_vm.go, client_vm_test.go, mock_vm_create.go
Before this fix the GET / LIST calls for VMs would fail with the message "no initialization field found on VM object" if there is no initialization set. However, creation would not fail. This change fixes that issue and adds a test to make sure this is actually fixed. The test has been verified against the oVirt engine.
Yes
Yes
=> Fixes #110: No more failure on missing initialization

.github/workflows/compile-and-pack-tests.yml, go-ovirt-client-tests.spec
Adding a workflow and spec file to compile go-ovirt-client
tests to a binary file and deploy it as go-ovirt-client-tests RPM
...
...
...
=> add workflow and spec file for tests packing

client_disk_attachment_test.go, client_disk_create.go, client_disk_test.go, client_disk_uploadimage.go, client_disk_uploadimage_test.go, client_vm.go, client_vm_create.go, client_vm_test.go, errors.go, go.sum, mock_disk.go, mock_disk_downloadimage.go, mock_template_create.go, mock_vm_create.go
This PR fixes #129 and adds the sparse flag for creating virtual machines.
Yes
Yes
=> Fixes #129: Sparse support on VM creation

errors.go, new_test.go, test_helper.go
This PR fixes #55 and correctly identifies bad oVirt engine URLs with redirects.
Yes
Yes
=> Fixes #55: Incorrect oVirt Engine API URL not correctly identified

.github/workflows/build.yml
Removing setting up go tooling before running the golangci-lint action because it leads to a bug. This tooling is no longer needed anyway because we no longer need to run `go generate` before linting.
Yes
Yes
=> Remove setting up Go tooling before golangci-lint

client_template.go, client_template_get_blank.go, client_template_get_blank_test.go, mock_template_get_blank.go
This PR adds blank template detection based on several factors. This fixes [BZ 1858418](https://bugzilla.redhat.com/show_bug.cgi?id=1858418)
Currently implemented:
Yes
Yes
=> Blank template handling

vm_get_by_name.go
This PR fixes #180 and returns an error if no VM is found.
Yes
Yes
=> Fixes #180: Getting VM by name doesn't return an error if no VM is found

credential_shift_test.go, go.mod, go.sum, new.go, new_test.go, util_test.go
This PR fixes #183 and adds support for proxy servers in front of the oVirt engine. This change depends on oVirt/ovirt-engine-sdk-go#239.
Yes
Yes
=> Fixes #183: Adding support for proxies

vm.go
The changes in this PR lets the linter pass for the new [golangci-lint v1.46.0](https://github.com/golangci/golangci-lint/releases/tag/v1.46.0)
yes
yes
=> added nolint to pass new golangci-lint v1.46.0

vm_optimize_pinning.go
This PR adds the missing default retry values for optimizing the VM CPU pinning settings.
Yes
Yes
=> Added missing default retry values for optimizing VM CPU settings

README.md, doc.go, scripts/get_test_image/get_test_image.go, tls.go, tls_test.go
This change fixes the comments to indicate that golang/go#46287 has now been fixed and certificate pools are available in Go 1.18 and up.
Yes
Yes
=> Fixed comments about the certificate pool not being available on Windows

const.go, disk.go, disk_create.go
Currently, only during disk creation the size is validated [see here](https://github.com/oVirt/go-ovirt-client/blob/main/disk_create.go#L66-L76). 
This PR adds 
- a validation check for updating the disk
- and introduces the min. disk size for oVirt as exported constant
yes
yes
=> added disk size validation for update disk params

vm.go, vm_create.go, vm_test.go
This PR implements maximum memory handling in the memory policy.
Yes
Yes
=> Implemented max memory

util_test_helper.go, vm.go, vm_create.go, vm_test.go
Adding support for memory ballooning. It also changes the return of the `MemoryPolicy()` function as I discovered that it is always present.
Yes
Yes
=> Adding ballooning support

vm_create.go, vm_test.go
In this PR the defined constant `DefaultBlankTemplateID` is being used instead of an inline defined constant when creating a VM and clone is true. 
yes
yes
=> use default blank template ID const when vm clone is true

affinitygroup_get_by_name.go
This PR fixes a bug discovered by @eslutsky:
```
DEBUG panic: runtime error: index out of range [0] with length 0 
DEBUG                                              
DEBUG goroutine 59 [running]:                      
DEBUG github.com/ovirt/go-ovirt-client.(*oVirtClient).GetAffinityGroupByName.func1() 
DEBUG     /root/installer/terraform/providers/ovirt/vendor/github.com/ovirt/go-ovirt-client/affinitygroup_get_by_name.go:42 +0x6a5 
```
Yes
Yes
=> Fixes crash when no affinity groups are present with a given name

errors.go, retry.go
This change detects the following error and converts it into a nicer error message:
```
Cannot run VM: VM is locked. Please try again in a few minutes.
```
Yes
Yes
=> Detect locked VM and issue proper error code

retry.go
This PR replaces this:
```
maximum retries reached while trying to waiting for VM
```
With this:
```
maximum retries reached while waiting for VM
```
Yes
Yes
=> Fixed error message when reaching maximum retries

disk_remove_test.go, vm_test.go
Following tests were failing on live backend due to VMs not being able to start
because the disks created during the execution were not bootable and were
not activated:
TestNegativeVMAffinityShouldResultInDifferenHosts
TestDiskRemoveFromRunningVMShouldResultInError
TestVMStartStop
This PR aims to fix that. 
Yes
Yes
=> Fix tests failing due to disks not bootable

new_test.go, util_test.go, vm.go, vm_create.go, vm_test.go
This PR adds the `SoundcardEnabled` flag to the VM as well as the Builder. This is necessary for 
- https://issues.redhat.com/browse/OCPRHV-794
- https://issues.redhat.com/browse/OCPRHV-785
yes
yes
=> OCPRHV-794: added soundcard enabled flag to builder and VM

vm.go
This PR fixes the soundcard enabled field. Since `soundcard_enabled` is excluded by ovirt-engine, the field is set to the default bool value to prevent failing requests. 
yes
yes
=> use default value for soundcard_enabled

.golangci.yml, CONTRIBUTING.md, affinitygroup_list.go, disk_attachment_list.go, disk_downloadimage_test.go, disk_update.go, disk_uploadimage.go, errors.go, retry_test.go, scripts/get_test_image/get_test_image.go, scripts/rest/rest.go, tls.go, util_random.go, util_test.go, vm.go
This PR fixes a panic due to a nil reference when the `StartUpdateDisk` function fails. 
Update: 
Due to using golangci-lint v1.48.0 and Go 1.19 in the pipeline, there are additional lint fixes. Among them is the replacement of the deprecated `io/ioutil` package. Functions from this package where replaced according to documentation: https://pkg.go.dev/io/ioutil
yes
yes
=> fixed panic on failed update disk

.golangci.yml, instancetype_get.go, vm.go, vm_create.go, vm_get.go, vm_get_by_name.go, vm_list.go, vm_search.go, vm_update.go
This PR fixes [OCPRHV-856](https://issues.redhat.com/browse/OCPRHV-856) by removing the log statement (as well as fixing some lint errors). 
As stated in the [oVirt engine api documentation](http://ovirt.github.io/ovirt-engine-api-model/master/#services/vm/methods/get/parameters/all_content), the `console` field is only returned if the query parameter `all_content` is set to true. Due to performance issues this parameter is always false and will, therefore, never return the console object. 
yes
yes
=> OCPRHV-856 - removed error log for console not found

errors.go
This PR adds an additional error code for the user account being locked or disabled to further improve the logging (e.g. for [OCPRHV-698](https://issues.redhat.com/browse/OCPRHV-698) and [OCPRHV-695](https://issues.redhat.com/browse/OCPRHV-695))
yes
yes
=> added error code when user is locked

disk_helper_imagetransfer.go, new.go, newmock.go, nic.go, nic_create.go, nic_create_test.go, nic_test.go, nic_update.go, nic_update_test.go, util_test_helper.go, util_wait_for_job_finished.go
Allow manage and read MAC address of VM NIC interfaces.
Issue reference in terraform client: [issue](https://github.com/oVirt/terraform-provider-ovirt/issues/484) 
...
Yes
...
Yes
...
=> Extend nic with mac

.golangci.yml, vm.go, vm_create.go, vm_test.go, vm_update.go
Extend ability of go-ovirt-client to work with Description of VM. 
oVirt SDK can work with Description but go-ovirt-client lost one.
It PR add ability to work with Description
It code is written by me personally on personal workstation in my spare time.
I agree with BSD 3 license
=> Extend vm description
